### login de usuario 
POST http://localhost:3000/auth/login
Content-Type:   application/json

{
    "username": "profesor",
    "password": "1234"
}


### consultar todas las peliculas
GET http://localhost:3000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzQ3NDkwLCJleHAiOjE3NzYzNTIyOTB9.lM_VjGjSqPAfPSF5t5Vfd5tbs1K38WBiATgJpEEXM9s
### consultar una pelicula por id
GET http://localhost:3000/movies/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzQ3NDkwLCJleHAiOjE3NzYzNTIyOTB9.lM_VjGjSqPAfPSF5t5Vfd5tbs1K38WBiATgJpEEXM9s
### crear
POST http://localhost:3000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzQ3NDkwLCJleHAiOjE3NzYzNTIyOTB9.lM_VjGjSqPAfPSF5t5Vfd5tbs1K38WBiATgJpEEXM9s
Content-Type:   application/json

{
    "title": "The Matrix Recargado",
    "director": [2,3],
    "poster_url": "https://m.media-amazon.com/images/I/51EG732BV3L.jpg",
    "genre": [1]
}

### actualizar
PUT http://localhost:3000/movies/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzQ3NDkwLCJleHAiOjE3NzYzNTIyOTB9.lM_VjGjSqPAfPSF5t5Vfd5tbs1K38WBiATgJpEEXM9s
Content-Type:   application/json

{
  "title": "The Matrix Reloaded"
}

### eliminar 
DELETE http://localhost:3000/movies/18
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzQ3NDkwLCJleHAiOjE3NzYzNTIyOTB9.lM_VjGjSqPAfPSF5t5Vfd5tbs1K38WBiATgJpEEXM9s

###Obtener todos los generos
GET http://localhost:3000/genres
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzQ3NDkwLCJleHAiOjE3NzYzNTIyOTB9.lM_VjGjSqPAfPSF5t5Vfd5tbs1K38WBiATgJpEEXM9s

### consultar una genero por id
GET http://localhost:3000/genres/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzQ3NDkwLCJleHAiOjE3NzYzNTIyOTB9.lM_VjGjSqPAfPSF5t5Vfd5tbs1K38WBiATgJpEEXM9s

POST http://localhost:3000/genres
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzAzMDUxLCJleHAiOjE3NzU3MzkwNTF9.qiEZF8JQ61h9wFmv7R5EeWz-2dFFJLGMPrrVjMjeLOg
Content-Type: application/json

{
  "name": "Sci-Fi"
}

###Actualizar genero

PUT http://localhost:3000/genres/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzQ3NDkwLCJleHAiOjE3NzYzNTIyOTB9.lM_VjGjSqPAfPSF5t5Vfd5tbs1K38WBiATgJpEEXM9s

{
  "name": "Ciencia Ficcion"
}

###Eliminar genero

DELETE http://localhost:3000/genres/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzQ3NDkwLCJleHAiOjE3NzYzNTIyOTB9.lM_VjGjSqPAfPSF5t5Vfd5tbs1K38WBiATgJpEEXM9s
###Consultar los directores
GET http://localhost:3000/directors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzQ3NDkwLCJleHAiOjE3NzYzNTIyOTB9.lM_VjGjSqPAfPSF5t5Vfd5tbs1K38WBiATgJpEEXM9s
### consultar una director por id
GET http://localhost:3000/directors/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzQ3NDkwLCJleHAiOjE3NzYzNTIyOTB9.lM_VjGjSqPAfPSF5t5Vfd5tbs1K38WBiATgJpEEXM9s
### crear director
POST http://localhost:3000/directors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzQ3NDkwLCJleHAiOjE3NzYzNTIyOTB9.lM_VjGjSqPAfPSF5t5Vfd5tbs1K38WBiATgJpEEXM9s
Content-Type: application/json

{
  "full_name": "Francis Ford Coppola"
}

###Actualizar director

PUT http://localhost:3000/directors/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzQ3NDkwLCJleHAiOjE3NzYzNTIyOTB9.lM_VjGjSqPAfPSF5t5Vfd5tbs1K38WBiATgJpEEXM9s
Content-Type: application/json

{
  "full_name": "Francis Ford Coppola"
}

###Eliminar director

DELETE http://localhost:3000/directors/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJwcm9mZXNvciIsImVtYWlsIjoicHJvZmVzb3JAY2xhc2UuZWR1IiwiaWF0IjoxNzc1NzQ3NDkwLCJleHAiOjE3NzYzNTIyOTB9.lM_VjGjSqPAfPSF5t5Vfd5tbs1K38WBiATgJpEEXM9s

