### login de usuario 
POST http://localhost:3000/auth/login
Content-Type:   application/json

{
    "username": "profesor",
    "password": "hash_falso_123"
}




### consultar todas las peliculas
GET http://localhost:3000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzc1NjMyNzQ5LCJleHAiOjE3NzU2Njg3NDl9._UlRNibdQxm35enmAvwa8v48F8MC7r0IFpV4-Np8iGA

### consultar una pelicula por id
GET http://localhost:3000/movies/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzc1NjMyNzQ5LCJleHAiOjE3NzU2Njg3NDl9._UlRNibdQxm35enmAvwa8v48F8MC7r0IFpV4-Np8iGA

### crear
POST http://localhost:3000/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzc1NjMyNzQ5LCJleHAiOjE3NzU2Njg3NDl9._UlRNibdQxm35enmAvwa8v48F8MC7r0IFpV4-Np8iGA
Content-Type:   application/json

{
    "title": "The Matrix Recargado",
    "director": [2,3],
    "posterUrl": "https://m.media-amazon.com/images/I/51EG732BV3L.jpg",
    "genre": [
        1,2
    ]
}

### eliminar
DELETE http://localhost:3000/movies/1234
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzc1NjMyNzQ5LCJleHAiOjE3NzU2Njg3NDl9._UlRNibdQxm35enmAvwa8v48F8MC7r0IFpV4-Np8iGA
### actualizar
PUT http://localhost:3000/movies/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzc1NjMyNzQ5LCJleHAiOjE3NzU2Njg3NDl9._UlRNibdQxm35enmAvwa8v48F8MC7r0IFpV4-Np8iGA
Content-Type:   application/json

{
    "title": "The Matrix Reloaded",
    "director": [4,1]
}

### eliminar un recurso
DELETE http://localhost:3000/movies/1234
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzc1NjMyNzQ5LCJleHAiOjE3NzU2Njg3NDl9._UlRNibdQxm35enmAvwa8v48F8MC7r0IFpV4-Np8iGA

###Obtener todos los géneros
GET http://localhost:3000/genres
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzc1NjMyNzQ5LCJleHAiOjE3NzU2Njg3NDl9._UlRNibdQxm35enmAvwa8v48F8MC7r0IFpV4-Np8iGA

### consultar una genero por id
GET http://localhost:3000/genres/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzc1NjMyNzQ5LCJleHAiOjE3NzU2Njg3NDl9._UlRNibdQxm35enmAvwa8v48F8MC7r0IFpV4-Np8iGA

### crear genero
POST http://localhost:3000/genres
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzc1NjMyNzQ5LCJleHAiOjE3NzU2Njg3NDl9._UlRNibdQxm35enmAvwa8v48F8MC7r0IFpV4-Np8iGA
Content-Type: application/json

{
  "name": "Sci-Fi"
}

###Actualizar genero

PUT http://localhost:3000/genres/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzc1NjMyNzQ5LCJleHAiOjE3NzU2Njg3NDl9._UlRNibdQxm35enmAvwa8v48F8MC7r0IFpV4-Np8iGA
Content-Type: application/json

{
  "name": "Ciencia Ficcion"
}

###Eliminar genero

DELETE http://localhost:3000/genres/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJtaWRvbWluaW8uY29tIiwidXNlcm5hbWUiOiJwcm9mZXNvciIsInJvbCI6ImFkbWluIiwiaWF0IjoxNzc1NjMyNzQ5LCJleHAiOjE3NzU2Njg3NDl9._UlRNibdQxm35enmAvwa8v48F8MC7r0IFpV4-Np8iGA

